project_id = "ikabtkxxjqbonqykzsan"

[functions.daydream-stream]
verify_jwt = false

[functions.daydream-prompt]
verify_jwt = false

[functions.livepeer-clip]
verify_jwt = false

[functions.generate-ticket]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.redeem-ticket]
verify_jwt = false
